M48
; DRILL file {KiCad 9.0.2} date 2025-11-09T22:55:29+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-09T22:55:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X75.906Y-62.912
X82.733Y-187.143
X243.46Y-92.576
X339.342Y-205.986
M30
